title: Goeun-Oh
description: Digital Circuit Engineer
#site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: goeun-oh
#blog_url: https://www.nagekar.com
email: qw433812@gmail.com
#keybase_username: abhn
#twitter_username: abhn_
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pic.jpg

# Google Analytics ID
# google_analytics: 